### ISSUE TITLE
Thread not properly killed on end play

### ISSUE THREAD

**Issue by andreihaidu** [robcog-iai/UROSBridge#16]
```
LogStats: Warning: MetaData mismatch. Did you assign a stat to two groups? New //STATGROUP_Threads//ROSBridgeHandlerRunnable///Thread_3244_0///####STATCAT_Advanced#### old //STATGROUP_Threads//ROSBridgeHandlerRunnable///Thread_1ed4_0///####STATCAT_Advanced####
```

It should not affect usability.

See https://answers.unrealengine.com/questions/166882/logstatswarning-metadata-mismatch.html 

Steps to reproduce:

Start world using the ROS handler (`FROSBridgeHandler`) in an actor. Stop world. Start again. Warning appears. It seems that the previous thread is still living in the editor, and when the new one is created the same name is used, hence the warning.

**Comment by aaronsnoswell** [comment]
I've seen this too. Does this only occur when in editor?

**Comment by andreihaidu** [comment]
workaround by appending an incrementing index to thread name, it gets rid of the warning, however the thread might still be idling in the background. (https://github.com/robcog-iai/UROSBridge/blob/master/Source/UROSBridge/Private/ROSBridgeHandler.cpp#L299)
