### ISSUE TITLE
Compile error on WebSocket.cpp

### ISSUE THREAD

**Issue by jacobdeery** [robcog-iai/UROSBridge#32]
Running Unreal 4.18 on Ubuntu 16.04.

When I try to build this plugin I get a compile error:

```
ThirdParty/OpenSSL/1_0_2h/include/Linux/x86_64-unknown-linux-gnu/openssl/ossl_typ.h:172:9: error: 
      'UI' macro redefined [-Werror,-Wmacro-redefined]
#define UI OSSL_UI
        ^
/home/jd/development/anm_unreal_sim/submodules/base_unreal_project/Plugins/UROSBridge/Source/UROSBridge/Private/WebSocket.cpp:26:9: note: 
      previous definition is here
#define UI UI_ST
```

However, if I comment out lines 26 & 30 on WebSocket.cpp (`#define UI UI_ST` and `#undef UI`), the plugin compiles without errors.

**Comment by andreihaidu** [comment]
Hi, thanks for the input. This error should not appear in 4.19. However your workaround is correct.
