### ISSUE TITLE
UE4Bson in branch dev-bson

### ISSUE THREAD

**Issue by mp3242** [robcog-iai/UROSBridge#45]
Hello, simple question. I'd like to try out the bson functionality in dev-bson but I get a message that I don't have the UE4Bson module. How would I go about adding it?

**Comment by andreihaidu** [comment]
Hi @Sanic , one of your students worked on the bson implementation, do you know if it works or is anybody going to maintain it? If not we should mark it as abandoned.

**Comment by andreihaidu** [comment]
UPODATE @mp3242 this is discontinued/on hold for an unknown time.

**Comment by Sanic** [comment]
@mp3242 Thanks for your interest in the BSON functionality.
As Andrei already pointed out, we're currently focussing on our things and don't have priority on this branch.
But if you wanna still try the functionality out, i've put the UE4Bson module in a repository for you: https://github.com/code-iai/UE4Bson
The module was implemented when 4.19 was hot and it tried to mimic the standard JSON UE4 api was much as possible.

**Comment by mp3242** [comment]
@Sanic Thank you! This is good enough for me to get started.
